name: 'VSCE package'
run-name: "VSCE package"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  CreateApp:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install ${{ github.workspace }}/Git-to-AL-project-configurator/
    - name: Install vsce globally
      run: npm install -g vsce
    - name: package vsc Install
      run: |
        cd ${{ github.workspace }}/Git-to-AL-project-configurator/
        vsce package --out ${{ github.workspace }}/GitToALProjectCfg.vsix
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
          name: name.vsix
          path: ${{ github.workspace }}/GitToALProjectCfg.vsix
          if-no-files-found: error
    - name: Upload Repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update repository with new version of vsix
